[build]
  functions = "netlify/functions"

[functions.auth]
  origin = "https://star-wallet.netlify.app"

[functions.save-addresses]
  origin = "https://star-wallet.netlify.app"

[functions.save-seed]
  origin = "https://star-wallet.netlify.app"



